services:
#  postgres:
#    container_name: postgres-sql-bsn
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 2004
#      POSTGRES_DB: book_social_network
#    ports:
#      - 5433:5432
#    networks:
#      - spring-demo
#    volumes:
#      - postgres-student-data:/var/lib/postgresql/data

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres-student-data:
